## Optional settings for the run
overwrite_if_output_directory_exists : True
output_individual_realizations : True

## Input information
input_directory : "input_files"
env_file_name : ".env_home"
initial_input_file_name : "simple_input.toml"
locations : ["AKL","WLG","CHC"]

## Output information
output_directory : "/home/arr65/data/nshm/output_test"
collated_notes_file_name : "collated_notes.csv"