[general]
compatibility_key = "NZSHM22-0"
hazard_model_id = "DEMO_MODEL"

[logic_trees]
model_version = "NSHM_v1.0.4"
#model_version = "NSHM_v1.0.0"
#model_version = "test"

# alternatively, specify a path to logic tree files
#srm_file = "demo/srm_logic_tree_no_slab.json"
#gmcm_file = "demo/gmcm_logic_tree_medium.json"
#gmcm_file = "../demo/gmcm_logic_tree_small.json"
#gmcm_file = "/home/arr65/src/logic_tree_study/custom_logic_trees/gmcm_logic_tree_small.json"

#srm_file = "../demo/srm_logic_tree.json"
#gmcm_file = "/home/arr65/src/logic_tree_study/custom_logic_trees/gmcm_logic_tree_small.json"

[site]
#vs30s = [275, 400]
vs30s = [275]
locations = ["CHC"]

[calculation]
#imts = ["PGA", "SA(0.2)", "SA(0.5)", "SA(1.5)", "SA(3.0)", "SA(5.0)"]

imts= ['PGA','SA(0.1)', 'SA(0.15)', 'SA(0.2)', 'SA(0.25)', 'SA(0.3)', 'SA(0.35)', 'SA(0.4)', 'SA(0.5)', 'SA(0.6)',
    'SA(0.7)', 'SA(0.8)', 'SA(0.9)', 'SA(1.0)', 'SA(1.25)', 'SA(1.5)', 'SA(1.75)', 'SA(2.0)', 'SA(2.5)', 'SA(3.0)',
	'SA(3.5)', 'SA(4.0)', 'SA(4.5)', 'SA(5.0)', 'SA(6.0)', 'SA(7.5)', 'SA(10.0)']

#agg_types = ["mean", "cov", "std", "0.1", "0.005", "0.01", "0.025"]
#agg_types = ["mean", "cov", "std", "0.1", "0.005", "0.01", "0.025"]
agg_types = ["mean", "cov", "std", '0.005', '0.01', '0.025', '0.05', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7',
	'0.8', '0.9', '0.95', '0.975', '0.99', '0.995']

#imts = ["PGA"]
#agg_types = ["mean"]
#agg_types = ["mean","std"]
