## Settings for the run
delete_existing_output : True
output_individual_realizations : False

## Input information
input_directory : "custom_input_files"
env_file_name : ".env_home"
initial_input_file_name : "simple_input.toml"

#locations : ["AKL","WLG","CHC"]
locations : ["WLG"]

## Output information
output_directory : "/home/arr65/data/nshm/auto_output/auto24"
run_notes_file_name : "run_notes.csv"




