AbrahamsonEtAl2014 = "tab:olive"
Atkinson2022Crust = "tab:orange"
BooreEtAl2014 = "tab:green"
Bradley2013 = "tab:red"
CampbellBozorgnia2014 = "tab:purple"
ChiouYoungs2014 = "tab:brown"
Stafford2022 = "tab:blue"
Atkinson2022SInter = "tab:blue"
NZNSHM2022_AbrahamsonGulerce2020SInter = "tab:orange"
NZNSHM2022_KuehnEtAl2020SInter = "tab:green"
NZNSHM2022_ParkerEtAl2020SInter = "tab:red"
Atkinson2022SSlab = "tab:olive"
NZNSHM2022_AbrahamsonGulerce2020SSlab = "tab:brown"
NZNSHM2022_KuehnEtAl2020SSlab = "tab:purple"
NZNSHM2022_ParkerEtAl2020SSlab = "tab:gray"
CRU_deformation_model = "tab:blue"
CRU_time_dependence = "tab:orange"
CRU_MFD = "tab:green"
CRU_moment_rate_scaling = "tab:red"
INTER_HIK_and_PUY_MFD = "tab:purple"
INTER_HIK_and_PUY_moment_rate_scaling = "tab:brown"

## Tableau colors 
## ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple', 'tab:brown', 'tab:pink', 'tab:gray', 'tab:olive', 'tab:cyan']
