[general]
compatibility_key = "NZSHM22-0"
hazard_model_id = "DEMO_MODEL"

[logic_trees]
#model_version = "NSHM_v1.0.4"

# alternatively, specify a path to logic tree files
srm_file = "/home/arr65/src/nshm_logic_tree_utilities/custom_logic_trees/slt_full_NSHM_v1.0.4.json"
gmcm_file = "/home/arr65/src/logic_tree_study/custom_logic_trees/glt_full_NSHM_v1.0.4.json"




[site]
#vs30s = [275, 400]
vs30s = [400]
locations = ["CHC"]

[calculation]

imts= ['PGA']

agg_types = ["mean", "cov", "std"]

